### ISSUE TITLE
ModuleNotFoundError: No module named 'models.networks.loss'

### ISSUE THREAD

**Issue by eytanlevit** [lsfhuihuiff/PLDGAN#1]
When executing "python test.py --no_instance --no_flip"

Full traceback:
Traceback (most recent call last):
  File "/home/eytan/code/PLDGAN/test.py", line 11, in <module>
    from models.pix2pix_model import Pix2PixModel
  File "/home/eytan/code/PLDGAN/models/pix2pix_model.py", line 7, in <module>
    import models.networks as networks
  File "/home/eytan/code/PLDGAN/models/networks/__init__.py", line 8, in <module>
    from models.networks.loss import *
ModuleNotFoundError: No module named 'models.networks.loss'

Running with Python 3.11.7

**Comment by Norod** [comment]
@eytanlevit Looks like these files are indeed missing. 
Try cloning [this repo](https://github.com/ai-forever/ghost) and then copy the missing files from https://github.com/ai-forever/ghost/tree/main/models/networks as well as copy in this entire folder https://github.com/ai-forever/ghost/tree/main/utils into a new PLDGAN\utils sub-folder

If you then get a cv2 error try pip install opencv-python-headless

**Comment by lsfhuihuiff** [comment]
I'm sorry, we have already supplemented the missing files.
